name: github_actions_gtest_example-Debug

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "create and enter build dir"
        run: mkdir build && cd build
      - name: "run cmake "
        run: cmake ..
      - name: "run make " 
        run: cd build && cmake --build -S .
