name: github_actions_gtest_example-Debug

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate
        run: mkdir build && cd build && cmake -S ../..
      - name: Build
        run: cd build && cmake --build .
