name: github_actions_gtest_example-Debug

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "create and enter build dir"
        run: |
          ls
          cd ..
      - name: "run cmake "
        run: ls
      - name: "run make " 
        run: cd .. & ls
